### ISSUE TITLE
Inconsistent triggering of anonymous transition after guarded transition

### ISSUE THREAD

**Issue by sweatybridge** [boostorg/msm#16]
Hi Christophe,

I'm facing an unexpected behavior in the following transition table:
```cpp
    // guards
    struct validate {
        template<class Event, class FSM, class SourceState, class TargetState>
        bool operator()(const Event& e, FSM&, SourceState&, TargetState&)
        {
            return e.value > 0;
        }
    };

    // state machine properties
    typedef boost::mpl::vector2<Running, Init> initial_state;

    // Transition table for traceroute
    struct transition_table : boost::mpl::vector<
        //    Start      Event           Next      Action                     Guard
        //  +----------+---------------+-----------+------------------------+--------------------+
    bmf::Row< Running  , success       , bmf::none , log_action             , validate           >,
        //  +---------+-------------+---------+---------------------------+----------------------+
    bmf::Row< Init     , success       , Idle      , log_action             , bmf::none          >,
    bmf::Row< Init     , failure       , Idle      , log_action             , bmf::none          >,
    bmf::Row< Idle     , bmf::none     , Completed , log_action             , bmf::none          >
        //  +---------+-------------+---------+---------------------------+----------------------+
    > {};
```

The problem is when the `validate` guard returns false, the second orthogonal region correctly transitions to the `Idle` state but does not perform the anonymous transition from `Idle` to `Completed`. If I remove the first orthogonal region from the transition table, the anonymous transition is performed as expected.

I think this behavior is inconsistent and would like to get your help in fixing it. The full program is posted here: https://gist.github.com/sweatybridge/b9b5d08046aee63e98d05653e7288fdf.

Hope to hear from you soon.

Warm Regards,
Han

**Comment by henry-ch** [comment]
Test works for me. Added Unit Test to check it in future.

**Comment by sweatybridge** [comment]
Hello @henry-ch, did you check the stdout of the test? The test for `success0Bad` will run successfully but the end state is not correct.

What it prints is

```
    // Expected:
    // src: N3Bug4InitE dst: N3Bug4IdleE
    // src: N3Bug4IdleE dst: N3Bug9CompletedE
```

But the correct state should be
```
    // Actual:
    // src: N3Bug4InitE dst: N3Bug4IdleE
```

**Comment by henry-ch** [comment]
I did of course. Under Windows (more readable) I get:
src: struct Bug::Init dst: struct Bug::Idle
src: struct Bug::Idle dst: struct Bug::Completed

**Comment by sweatybridge** [comment]
That's great. I was worried that the original issue wasn't clear.

Thank you for providing more details of the fix, especially for those who missed the context.

**Comment by henry-ch** [comment]
I do not know what actually fixed the issue, so I unfortunately have no details.
