### ISSUE TITLE
Compilation time with MSM

### ISSUE THREAD

**Issue by timetrap** [boostorg/msm#17]
Compiling a C++ file with over 20 states takes over 9GB of ram and takes over an hour to compile. It is creating a large object file with over half of the symbols coming from msm. Is there any solutions to this?

**Comment by henry-ch** [comment]
A few:

- https://www.boost.org/doc/libs/1_84_0/libs/msm/doc/HTML/ch03s05.html#d0e2542
- upcoming backend11
- redesigning the FSM. 20 States just has a feeling of monolith
