### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by traceon** [boostorg/msm#20]
Since Boost.MSM provides best-in-class performance, and, arguably, functionality, I would like to use it in a production code where the final execution speed/latency is a paramount, and not the ease of use/adoption, or executable size, or compilation time. In my use case I'll have to make the very base of the infrastructural/chassis code to depend on MSM. However, the activity of this project, or should I say lack of it, is a bit worrying.

So I kindly ask the maintainers to share their vision on the MSM future.

Thanks!

**Comment by chaoflow** [comment]
@pdimov You've been recently making commits. Is boost msm maintained?

**Comment by pdimov** [comment]
Not by me. The author and maintainer is Christophe Henry (@henry-ch) (https://github.com/boostorg/boost/blob/47958e0cad3b8c4f58481f5236c4732b863357a1/libs/maintainers.txt#L97), but he doesn't seem active. Maybe @mjcaisse knows more.

**Comment by chaoflow** [comment]
@pdimov Thank you for the fast response!

**Comment by mjcaisse** [comment]
I have sent an email to Christophe and will respond if I hear back.

**Comment by henry-ch** [comment]
Hi, I'm back on it. MSM will get in 1.85 an update for the backend and a new C++20 front-end. Sorry for the long break.
