### ISSUE TITLE
msm/back/state_machine, new_state_helper boost::placeholders namespace missing at bind

### ISSUE THREAD

**Issue by BuzaL** [boostorg/msm#22]
https://github.com/boostorg/msm/blob/009e6ac8d57241956781296d713321a0868d00e0/include/boost/msm/back/state_machine.hpp#L2387
It could be a compile issue when using BOOST_BIND_NO_PLACEHOLDERS macro.

**Comment by BuzaL** [comment]
Similare issue can be found at MSM_VISITOR_ARGS_EXECUTE macro:
https://github.com/boostorg/msm/blob/009e6ac8d57241956781296d713321a0868d00e0/include/boost/msm/back/state_machine.hpp#L2308

**Comment by BuzaL** [comment]
my suggestion is, to insert using namespace after 2316 and 2324:
`		    using namespace ::boost::placeholders;                                          \`
Of course, where the SM will be included, should be include placeholders first.

**Comment by rogerorr** [comment]
With 1.73.0 you get a deprecation warning, which makes the problem noisier:
-- msm_declaration.cpp --
` #include <boost/msm/back/state_machine.hpp>`

```
cl /nologo /EHsc /I..\boost msm_deprecation.cpp /c
msm_deprecation.cpp
..\boost\boost/bind.hpp(41): note: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
```
