### ISSUE TITLE
GCC 11 rejects constructor syntax

### ISSUE THREAD

**Issue by mgaunard** [boostorg/msm#38]
For constructors of template classes, GCC 11 is stricter than previous versions and considers that repeating the template argument list is invalid syntax.
This means that Boost.MSM doesn't build with that compiler.

For example, In state_machine.hpp, the default constructor `state_machine<A0,A1,A2,A3,A4 >()` should just be declared as `state_machine()`, and likewise for all the others.

**Comment by Romain-Geissler-1A** [comment]
FYI, I submitted #PR 26 to fix it months ago. However this library seems abandoned since several years already...

**Comment by mgaunard** [comment]
Yeah, there are a bunch of libraries like that, usually maintained collectively by some committee within Boost.
Can try pinging @pdimov who did all recent changes to this repo.

**Comment by pdimov** [comment]
Resolved by #26.
