### ISSUE TITLE
compile break in 1.85.0.beta1 when using favor_compile_time

### ISSUE THREAD

**Issue by ChristophStrehle** [boostorg/msm#70]
When instantiating the boost::msm::back::state_machine template with the boost::msm::back::favor_compile_time back end I get the following compile break:

`boost\msm\back\metafunctions.hpp(651,50): error C2039: 'as_vector': is not a member of 'boost::fusion::result_of'`

**Comment by henry-ch** [comment]
fixed in develop. Will request merge into 1.85 master.
